version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres17
    restart: always
    environment:
      - POSTGRES_USER=user_delivery
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
